AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation template orchestrates the creation of IAM roles
  and EC2 instances using nested stacks.

Parameters:
  DeploymentBucket:
    Description: Name of the deployment bucket
    Type: String
    Default: dev-flask-lab
  EnvironmentName:
    Description: Name of the environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
      - test
  InstanceTypeParam:
    Description: Type of the EC2 instance
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t3.micro
      - t3.small
      - t3.medium

Resources:
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${DeploymentBucket}.s3.amazonaws.com/templates/iam.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${DeploymentBucket}.s3.amazonaws.com/templates/vpc.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IAMStack
      - VPCStack
    Properties:
      TemplateURL: !Sub https://${DeploymentBucket}.s3.amazonaws.com/templates/ec2.yaml
      Parameters:
        DeploymentBucket: !Ref DeploymentBucket
        InstanceTypeParam: !Ref InstanceTypeParam
        EnvironmentName: !Ref EnvironmentName
  ALBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - EC2Stack
    Properties:
      TemplateURL: !Sub https://${DeploymentBucket}.s3.amazonaws.com/templates/alb.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName